version: "3.3"
services:
  node-api:
    build: ./node-api
    volumes:
      - ./node-api:/usr/src/app
    ports:
      - 8080:8080
  website:
    image: nginx:alpine
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - 5001:80
    depends-on:
      - node-api
